# Generated by Django 4.2.16 on 2026-03-23 15:33

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UDFDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('record_type', models.CharField(choices=[('ticket', 'Ticket')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('udf_type', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('record_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UDFDefinitionTracker',
            fields=[
            ],
            options={
                'db_table': 'sync_udfdefinition',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sync.udfdefinition',),
        ),
    ]
