# Generated by Django 4.2.16 on 2026-03-19 11:56

import django.contrib.postgres.indexes
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('halo', '0030_ticket_created_ticket_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldInfoReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('field_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Field Info Reference',
                'verbose_name_plural': 'Field Info References',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['udf_data'], name='halo_ticket_udf_data_gin'),
        ),
    ]
