# Generated by Django 4.2.25 on 2026-04-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halo', '0031_fieldinforeference_ticket_udf_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='halo.agent')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='halo.team')),
            ],
            options={
                'verbose_name': 'Canned text',
                'verbose_name_plural': 'Canned texts',
            },
        ),
        migrations.CreateModel(
            name='CannedTextTracker',
            fields=[
            ],
            options={
                'db_table': 'halo_cannedtext',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('halo.cannedtext',),
        ),
    ]
