# Generated by Django 4.2.28 on 2026-06-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halo', '0032_cannedtext_cannedtexttracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
