# Generated by Django 4.2.28 on 2026-08-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halo', '0033_agent_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='halo.ticket')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='halo.milestone')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='halo.milestone')),
            ],
            options={
                'verbose_name_plural': 'Milestone Dependencies',
                'unique_together': {('child', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneDependencyTracker',
            fields=[
            ],
            options={
                'db_table': 'halo_milestonedependency',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('halo.milestonedependency',),
        ),
        migrations.CreateModel(
            name='MilestoneTracker',
            fields=[
            ],
            options={
                'db_table': 'halo_milestone',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('halo.milestone',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='halo.milestone'),
        ),
    ]
