# Generated by Django 4.2.16 on 2026-03-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udfdefinition',
            name='is_list',
        ),
    ]
